#! /usr/bin/env python 
__doc__="""
DESCRIPTION:

    Shows RSF data file (stdin) with python plotting interface

    OR

    Show characterization results of sfchar script (stdin). 
    It will show initial data, reconstructed data, and data overlayed 
    with singularity orders.


SYNTAX:    sfshow <input.rsf attrib=[alpha]/sigma/amplitude/phase/0 shift=0
           Null=chr.Null seismic=[0]/1 recons=[0]/1 label=[1]/0 save=[0]/1 
           name=section


ARGUMENTS: attrib  -- attribute of events to be plotted or 0

           Null    -- null value of standard input 
           shift   -- add a shift to attribute values
           seismic -- flag to show original seismic data
           recons  -- flag to show reconstructed data
           label   -- show labels of plots with headers info of stdin
           save    -- flag to save plotted figures

IO:        input.rsf  -- 3-D rsf file generated by sfchar.py OR
                         2-D seismic section

      
AUTHOR:    Mohammad Maysami
           Seismic Laboratory for Imaging and Modeling (SLIM)
           Department of Earth & Ocean Sciences (EOSC)
           The University of British Columbia (UBC)

LICENSE:   You may use this code only under the conditions and terms 
           of the license contained in the file LICENSE provided with
           this source code. If you do not agree to these terms you may 
           not use this software.
"""
 
import rsf as __rsf
from Charm.Core import Show   as __Show
from sys        import stderr as __stderr

par    = __rsf.Par()
help     = par.int('help')
if help:
    print >>__stderr,__doc__
    raise SystemExit

stdin  = __rsf.Input()
saveflag = par.int('save')
label    = par.int('label',default=1)
Null     = par.float('Null')
seisflag = par.int('seismic')
reconflag= par.int('recons')
shift    = par.int('shift')
attrib   = par.string('attrib')
savename = par.string('name')

# Zero Default Value doesn't work and sets to None
for (name, value) in __Show._par_dict.items():
    if eval('%s == None' %name):
        exec('%s = value' %name)
par_dict={'saveflag':saveflag,'savename':savename,'label':label,'Null':Null,
          'seisflag':seisflag,'reconflag':reconflag,'shift':shift,
          'attrib':attrib}


_im_dict ={'interpolation':'nearest','aspect':'auto'}

__Show.show_rsf(stdin,0,par_dict,label)

stdin.fileclose()


